#!/bin/bash

kmerLength=$1
sampleDirectory=$2
processors=$3
outputDirectory=$4

mkdir $outputDirectory
cd $outputDirectory

source $DARK_FISH_TECHNOLOGY

DarkFishTechnology_initializeDirectory

DarkFishTechnology_prepareSample $sampleDirectory

pairs=$(DarkFishTechnology_getPairs)

mpiexec -version &> meta/mpiexec.version
Ray -version &> meta/ray.version

command="mpiexec -output-filename ComputeCore -n $processors Ray -k $kmerLength $pairs -o Assembly "

searchBaseDirectory=$(DarkFishTechnology_getBaseSearchDirectory)

for i in $(ls $searchBaseDirectory)
do
	command=$command" -search $searchBaseDirectory/$i "
done

DarkFishTechnology_runCommand 0 "$command"

DarkFishTechnology_postProcessAssembly

cd Assembly/BiologicalAbundances

DetectLife.sh
