#!/bin/bash

kmerLength=$1
sampleDirectory=$2
processors=$3
outputDirectory=$4

mkdir $outputDirectory
cd $outputDirectory

source $DARK_FISH_TECHNOLOGY

DarkFishTechnology_initializeDirectory

DarkFishTechnology_prepareSample $sampleDirectory

pairs=$(DarkFishTechnology_getPairs)

mpiexec -version &> meta/mpiexec.version
Ray -version &> meta/ray.version

command="mpiexec -output-filename ComputeCore -n $processors Ray -k $kmerLength $pairs -o Assembly "

searchBaseDirectory=$(DarkFishTechnology_getBaseSearchDirectory)

if test -d $searchBaseDirectory
then

	for i in $(ls $searchBaseDirectory)
	do
		command=$command" -search $searchBaseDirectory/$i "
	done
fi

if test -f $TAXONOMY_DIRECTORY/Genome-to-Taxon.tsv
then
	command=$command" -with-taxonomy $TAXONOMY_DIRECTORY/Genome-to-Taxon.tsv $TAXONOMY_DIRECTORY/TreeOfLife-Edges.tsv $TAXONOMY_DIRECTORY/Taxon-Names.tsv "
fi

DarkFishTechnology_runCommand 0 "$command"

DarkFishTechnology_postProcessAssembly


