#!/bin/bash
# author: Sébastien Boisvert
# date: 2011-12-23

# this is some heavy scripting
# parallel machines in bash
# I use variable indirection

referenceFileOrigin=$1

# the argument must not be absolute paths.
sampleDirectoryOrigin=$2
processors=$3
output=$4

mkdir $output
cd $output

source $DARK_FISH_TECHNOLOGY

DarkFishTechnology_initializeDirectory

DarkFishTechnology_prepareReference $referenceFileOrigin
DarkFishTechnology_prepareSample $sampleDirectoryOrigin

DarkFishTechnology_runCommand 0 "bash --version &> meta/bash.version"
DarkFishTechnology_runCommand 0 "samtools &> meta/samtools.version"
DarkFishTechnology_runCommand 0 "bcftools &> meta/bcftools.version"
DarkFishTechnology_runCommand 0 "bwa &> meta/bwa.version"
DarkFishTechnology_runCommand 0 "samstat -help &> meta/samstat.version"
DarkFishTechnology_runCommand 0 "date > meta/date"
DarkFishTechnology_runCommand 0 "uname -a > meta/uname"
DarkFishTechnology_runCommand 0 "hostname > meta/hostname"

# for bwa
DarkFishTechnology_runCommand 0 "bowtie2-build Reference/Reference.fasta Reference/Reference.fasta"

# for samtools
DarkFishTechnology_runCommand 0 "samtools faidx Reference/Reference.fasta"

DarkFishTechnology_moveReferenceCache

# we have <processors> processors
# and we have n files
# the command is  bwa aln reference reads > sai
# we have to generate some variables

fileNumber=0

DarkFishTechnology_runCommand 0 "mkdir SamAlignments"

# generate alignments
for fileR1 in $(ls Sample|grep _R1_)
do
	fileR2=$(echo $fileR1|sed 's/_R1_/_R2_/g')
	fileRX=$(echo $fileR1|sed 's/_R1_/_RX_/g')

	processorNumber=$(($fileNumber%$processors))

	randomFile=$(DarkFishTechnology_generateCacheEntry)
	randomFiler1=$(DarkFishTechnology_generateCacheEntry)
	randomFiler2=$(DarkFishTechnology_generateCacheEntry)

	command="( zcat Sample/$fileR1 > $randomFiler1 ) ; "
	command=$command" ( zcat Sample/$fileR2 > $randomFiler2 ) ; "
	command=$command" DarkFishTechnology_linkCacheEntry $randomFiler1 SamAlignments $fileR1.fastq ; "
	command=$command" DarkFishTechnology_linkCacheEntry $randomFiler2 SamAlignments $fileR2.fastq ; "
	command=$command" ( bowtie2-align -x Reference/Reference.fasta -1 SamAlignments/$fileR1.fastq -2 SamAlignments/$fileR2.fastq | gzip > $randomFile ) ; "
	command=$command"  DarkFishTechnology_linkCacheEntry $randomFile SamAlignments $fileRX.sam.gz ; "

	processorVariable=processor$processorNumber"SamAlignments"
	oldValue=$(eval echo \$$processorVariable)

	newValue=$oldValue$command

	toEval="$processorVariable=\"$newValue\""

	eval $toEval

	fileNumber=$(($fileNumber+1))
done

DarkFishTechnology_runGroupCommands "SamAlignments"

DarkFishTechnology_finishAlignmentAnalysis
